# Generated by Django 3.0.2 on 2020-02-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[(0, 'First Phase'), (1, 'Second Phase'), (2, 'Semifinals'), (3, 'Final')], default=None, max_length=25, null=True),
        ),
    ]
