# Generated by Django 3.0.2 on 2020-02-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='phase',
            field=models.IntegerField(choices=[(0, 'First Phase'), (1, 'Second Phase'), (2, 'Semifinals'), (3, 'Final')], default=None, null=True),
        ),
    ]
