image: python:3

services:
  - postgres:latest

variables:
  POSTGRES_PASSWORD: ''
  POSTGRES_USER: postgres
  POSTGRES_DB: worldcup

before_script:
  - python -V
  - pip install -r requirements.txt
  - python manage.py migrate

test:
  script:
    - python manage.py test
