image: python:3

services:
  - postgres:latest

variables:
  POSTGRES_PASSWORD: ''
  POSTGRES_USER: postgres
  POSTGRES_DB: worldcup
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432

before_script:
  - python -V
  - pip install -r requirements.txt
  - python manage.py migrate

test:
  script:
    - python manage.py test
