version: '3'

services:
  db:
    image: postgres
    environment: 
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=worldcup
    volumes:
      - pgdata:/var/lib/posgresql/data
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/worldcup-api
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
volumes:
  pgdata: